/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2018-05-02 02:32:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.sqpicture.picture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class picture_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/sqpicture/picture/../../system/admin/top.jsp", Long.valueOf(1525223526306L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<!-- jsp文件头和头部 -->\r\n");
      out.write("\t");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.SYSNAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</title>\r\n");
      out.write("\t<meta name=\"description\" content=\"overview & stats\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t<!-- basic styles -->\r\n");
      out.write("\t<link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link href=\"static/css/bootstrap-responsive.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/font-awesome.min.css\" />\r\n");
      out.write("\t<!-- page specific plugin styles -->\r\n");
      out.write("\t<!-- 下拉框-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/chosen.css\" />\r\n");
      out.write("\t<!-- ace styles -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/ace.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/ace-responsive.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/ace-skins.min.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/datepicker.css\" /><!-- 日期框 -->\r\n");
      out.write("\t<!--引入弹窗组件start-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"plugins/attention/zDialog/zDrag.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"plugins/attention/zDialog/zDialog.js\"></script>\r\n");
      out.write("\t<!--引入弹窗组件end-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script>");
      out.write(" \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"static/css/imageHotAreaStyle.css\" />\r\n");
      out.write("\t</head> \r\n");
      out.write("<body>\r\n");
      out.write("\t\t\r\n");
      out.write("<div class=\"container-fluid\" id=\"main-container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"page-content\" class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("  <div class=\"row-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!-- 检索  -->\r\n");
      out.write("\t\t\t<form action=\"sqpicture/save.do\" method=\"post\" name=\"Form\" id=\"Form\">\r\n");
      out.write("  \r\n");
      out.write("\t\t\t    <div class=\"hot_area\" id = \"areaContent\">\r\n");
      out.write("     <!-- 1.图片url显示部分：-->\r\n");
      out.write("     <input id=\"\" type=\"text\"class=\"\" readonly=\"readonly\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 2.图片展示部分：-->\r\n");
      out.write("     <div class=\"\" name=\"imageMap\" id=\"image_map\">\r\n");
      out.write("       <img src=\"\"  ref=\"imageMap\" id=\"photo\"/>\r\n");
      out.write("     </div> \r\n");
      out.write("\r\n");
      out.write("    <!--3.添加热区对应编辑链接列表渲染部分，目前需两者选一：\r\n");
      out.write("     1)tablebody样式：-->\r\n");
      out.write("     <table><tbody id=\"areaItems\"> </tbody></table>\r\n");
      out.write("\r\n");
      out.write("    <!-- 2)ul样式：\r\n");
      out.write("     <ul id=\"areaItems\"></ul>-->\r\n");
      out.write("\r\n");
      out.write("    <!-- 4.添加热区按钮部分：-->\r\n");
      out.write("     <p><!-- <a id=\"add_hot_area\" href=\"JavaScript:;\" class=\"\">添加热区</a> --> &nbsp; <!-- <a id=\"\" href=\"JavaScript:viewMap();\" class=\"\">查看热区</a> --></p>\r\n");
      out.write("\t <p></p>\r\n");
      out.write("\r\n");
      out.write("    <!-- 5.热区数据存储（隐藏）：-->\r\n");
      out.write("     <!-- <input type=\"text\" class=\"\" id=\"hotAreas\" name=\"hotAreas\"  value=''> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- 6.可添加热区数量与还可添加热区数量实时显示（可选）：-->\r\n");
      out.write("     <p><span class=\"\">已添加<b class=\"added_amount\">0</b>个热区， 还可添加<b class=\"remain_amount\">X</b>个热区</span></p>\r\n");
      out.write("\r\n");
      out.write(" \t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"6\"  style=\"margin-top:20px;\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\">\r\n");
      out.write("                <a id=\"add_hot_area\" href=\"JavaScript:;\" class=\"btn btn-mini btn-primary\">添加热区</a>\r\n");
      out.write("\t                <a class=\"btn btn-mini btn-primary\" onClick=\"save();\">提交</a>\r\n");
      out.write("                </td>\r\n");
      out.write("                 \r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\t<!-- PAGE CONTENT ENDS HERE -->\r\n");
      out.write("  </div><!--/row-->\r\n");
      out.write("\t\r\n");
      out.write("</div><!--/#page-content-->\r\n");
      out.write("</div><!--/.fluid-container#main-container-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 返回顶部  -->\r\n");
      out.write("\t\t<a href=\"#\" id=\"btn-scroll-up\" class=\"btn btn-small btn-inverse\">\r\n");
      out.write("\t\t\t<i class=\"icon-double-angle-up icon-only\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 引入 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">window.jQuery || document.write(\"<script src='static/js/jquery-1.9.1.min.js'>\\x3C/script>\");</script>\r\n");
      out.write("\t\t<script src=\"static/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"static/js/ace.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/jquery.image-maps5.0.js\"></script><!-- 下拉框 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/chosen.jquery.min.js\"></script><!-- 下拉框 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/bootstrap-datepicker.min.js\"></script><!-- 日期框 -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/bootbox.min.js\"></script><!-- 确认窗口 -->\r\n");
      out.write("\t\t<!-- 引入 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"static/js/jquery.tips.js\"></script><!--提示框-->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(top.hangge());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t/* $('#imgMap').imageMaps();  */\r\n");
      out.write("\t\t\t//日期框\r\n");
      out.write("\t\t\t$('.date-picker').datepicker();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//下拉框\r\n");
      out.write("\t\t\t$(\".chzn-select\").chosen(); \r\n");
      out.write("\t\t\t$(\".chzn-select-deselect\").chosen({allow_single_deselect:true}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//复选框\r\n");
      out.write("\t\t\t/* $('table th input:checkbox').on('click' , function(){\r\n");
      out.write("\t\t\t\tvar that = this;\r\n");
      out.write("\t\t\t\t$(this).closest('table').find('tr > td:first-child input:checkbox')\r\n");
      out.write("\t\t\t\t.each(function(){\r\n");
      out.write("\t\t\t\t\tthis.checked = that.checked;\r\n");
      out.write("\t\t\t\t\t$(this).closest('tr').toggleClass('selected');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar floorList = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.floorList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\tvar gridList = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.gridList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t//$(function(){\r\n");
      out.write("\t\t\t\tvar setting = {\r\n");
      out.write("\t\t\t\t\tmaxAmount:100,\r\n");
      out.write("\t\t\t\t\ttag:'tr',\r\n");
      out.write("\t\t\t\t\tparams:{\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\t'gridList':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.gridList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(",\r\n");
      out.write("\t\t\t\t\t\t'floorList':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.floorList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(",\r\n");
      out.write("\t\t\t\t\t\t'hotList':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.hotList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t//proportion:\"0.5\",\r\n");
      out.write("\t\t\t\t\tdomCallBack:function(params){\r\n");
      out.write("\t\t\t\t\t\t//console.log(params);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t//初始化加载\r\n");
      out.write("\t\t\t\t//var areas = \"[{'areaTitle':'热区1','areaLink':'','areaMapInfo':'0,0,120,80'},{'areaTitle':'热区 2','areaLink':'','areaMapInfo':'260,13,353,112'}]\";\r\n");
      out.write("\t\t\t\tvar areas = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd.hotList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\t\t\t$(\"#hotAreas\").val(areas);  \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//$('#hotAreas').val('');     //清空热区数据\r\n");
      out.write("\t\t\t\t//$('#image_map').imageMaps(setting);\r\n");
      out.write("\t\t\t\t//imageMaps.originalManual(\"./size.jpg\",setting,true);\r\n");
      out.write("\t\t\t\timageMaps.proportionNoSameManual(\"static/img/sq001.jpg\",setting,1,1,false);\r\n");
      out.write("\t\t\t\t//\"hotAreas\" : \"[{'areaTitle':'热区1','areaLink':'','areaMapInfo':'0,0,90,30'},{'areaTitle':'热区 2','areaLink':'','areaMapInfo':'260,13,353,112'}]\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\tfunction editUser(user_id){\r\n");
      out.write("\t\t\t top.jzts();\r\n");
      out.write("\t\t\t var diag = new top.Dialog();\r\n");
      out.write("\t\t\t diag.Drag=true;\r\n");
      out.write("\t\t\t diag.Title =\"资料\";\r\n");
      out.write("\t\t\t diag.URL = '");
      out.print(basePath);
      out.write("user/goEditU.do?USER_ID='+user_id;\r\n");
      out.write("\t\t\t diag.Width = 225;\r\n");
      out.write("\t\t\t diag.Height = 415;\r\n");
      out.write("\t\t\t diag.CancelEvent = function(){ //关闭事件\r\n");
      out.write("\t\t\t\t if(diag.innerFrame.contentWindow.document.getElementById('zhongxin').style.display == 'none'){\r\n");
      out.write("\t\t\t\t\tsetTimeout(\"self.location.reload()\",100);\r\n");
      out.write("\t\t\t\t\ttop.jzts();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tdiag.close();\r\n");
      out.write("\t\t\t };\r\n");
      out.write("\t\t\t diag.show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction save(){\r\n");
      out.write("\t\t\t$(\"#Form\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction changeType(obj){\r\n");
      out.write("\t\t\tvar index = obj.id.substring(4);\r\n");
      out.write("\t\t\tvar value = obj.value;\r\n");
      out.write("\t\t\t$(\"#linkName\"+index).val(\"\");\r\n");
      out.write("\t\t\tif(value==0){\r\n");
      out.write("\t\t\t\t$(\"#typeName\"+index).val(\"网格\");\r\n");
      out.write("\t\t\t\tvar link = document.getElementById(\"linkId\"+index);\r\n");
      out.write("\t\t\t\tlink.length=1;\r\n");
      out.write("\t\t\t\tfor(var j=0;j<gridList.length;j++){\r\n");
      out.write("\t\t\t\t\tlink.options.add(new Option(gridList[j].NAME,gridList[j].ID));\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#typeName\"+index).val(\"楼\");\r\n");
      out.write("\t\t\t\tvar link = document.getElementById(\"linkId\"+index);\r\n");
      out.write("\t\t\t\tlink.length=1;\r\n");
      out.write("\t\t\t\tfor(var j=0;j<floorList.length;j++){\r\n");
      out.write("\t\t\t\t\tlink.options.add(new Option(floorList[j].NAME,floorList[j].ID));\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction changeLink(obj){\r\n");
      out.write("\t\t\tvar index = obj.id.substring(6);\r\n");
      out.write("\t\t\t$(\"#linkName\"+index).val(obj.options[obj.options.selectedIndex].innerHTML);\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
